# Custom shortcuts for splitting panes
bind s split-window -h
bind v split-window -v

# Navigate between panes with h, j, k, l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# (Optional) Enable mouse support for resizing panes
set -g mouse on
